### ISSUE TITLE
Newton-Raphson method in RiemannTrack

### ISSUE THREAD

**Issue by geniejhang** [SpiRIT-Collaboration/SpiRITROOT#18]
I found looking like a bug and sent an email to current maintainer of FOPIROOT.
He said even though the equation is not right, it worked properly up to now. 
I added the information directly [on the line](https://github.com/SpiRIT-Collaboration/SPiRITROOT/commit/e69cdaa14d0caffd785c007dbc4b4d2620fddabd#diff-6589150040c4354c682f9b7b51d177c4R738).

I'll keep updating what I found out.

**Comment by ejungwoo** [comment]
No more Riemann Tracking
