### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by geniejhang** [SpiRIT-Collaboration/SpiRITROOT#6]
Time unit, fm/c, in [Unit page](https://github.com/SpiRIT-Collaboration/SPiRITROOT/wiki/Unit#unit-used-throughout-the-software) is to short for simulation I think.

It's 3.336 * 10^-15 ns.

Isn't that in the result of generator data?

**Comment by ejungwoo** [comment]
https://github.com/SpiRIT-Collaboration/SpiRITROOT/wiki/Unit
